#ifndef USER_BOARD_H
#define USER_BOARD_H

#include <conf_board.h>

/*
 * Backlight control (SAMD21: PA07, Arduino: D9), active High.
 */
#define CONF_BOARD_BACKLIGHT_PIN PIN_PA07
#define CONF_BOARD_BACKLIGHT_TCC_MODULE TCC1
#define CONF_BOARD_BACKLIGHT_TCC_CHANNEL TCC_MATCH_CAPTURE_CHANNEL_1
#define CONF_BOARD_BACKLIGHT_TCC_PIN PIN_PA07E_TCC1_WO1
#define CONF_BOARD_BACKLIGHT_TCC_MUX MUX_PA07E_TCC1_WO1

/*
 * Onboard LEDs (marked as 'TX' (PA27) and 'RX' (PB03)), active low
 */
#define CONF_BOARD_LED_TX_PIN PIN_PA27
#define CONF_BOARD_LED_RX_PIN PIN_PB03

/*
 * Button (SAMD21: PA03, Pro Micro: AREF)
 */
#define CONF_BOARD_BUTTON_PIN PIN_PA03
#define CONF_BOARD_BUTTON_EIC_PIN PIN_PA03A_EIC_EXTINT3
#define CONF_BOARD_BUTTON_EIC_MUX MUX_PA03A_EIC_EXTINT3

/*
 * Row pin configuration (outputs)
 * Row:   0   1   2   3   4   5   6   7
 * Pin: D10 D11 D12 D13  A0  A1  A2  A3 (Arduino)
 * Pin:  B6  B2  B3  B1  F7  F6  F5  F4 (SAMD21 Mini Breakout)
 * Pin: A18 A16 A19 A17 A02 B08 B09 A04 (SAMD21)
 */
#define CONF_BOARD_MATRIX_DRIVE_0_PIN PIN_PA18
#define CONF_BOARD_MATRIX_DRIVE_1_PIN PIN_PA16
#define CONF_BOARD_MATRIX_DRIVE_2_PIN PIN_PA19
#define CONF_BOARD_MATRIX_DRIVE_3_PIN PIN_PA17
#define CONF_BOARD_MATRIX_DRIVE_4_PIN PIN_PA02
#define CONF_BOARD_MATRIX_DRIVE_5_PIN PIN_PB08
#define CONF_BOARD_MATRIX_DRIVE_6_PIN PIN_PB09
#define CONF_BOARD_MATRIX_DRIVE_7_PIN PIN_PA04

/*
 * Column pin configuration (inputs)
 * Col:   0   1   2   3   4   5   6   7   8
 * Pin:  D1  D0  D2  D3  D4  D5  D6  D7  D8 (Arduino)
 * Pin:  D3  D2  D1  D0  D4  C6  D7  E6  B4 (SAMD21 Mini Breakout)
 * Pin: A10 A11 A14 A09 A08 A15 A20 A21 A06 (SAMD21)
 */
#define CONF_BOARD_MATRIX_SENSE_0_PIN PIN_PA10
#define CONF_BOARD_MATRIX_SENSE_0_EIC_MUX MUX_PA10A_EIC_EXTINT10
#define CONF_BOARD_MATRIX_SENSE_0_EIC_PIN PIN_PA10A_EIC_EXTINT10
#define CONF_BOARD_MATRIX_SENSE_1_PIN PIN_PA11
#define CONF_BOARD_MATRIX_SENSE_1_EIC_PIN MUX_PA11A_EIC_EXTINT11
#define CONF_BOARD_MATRIX_SENSE_1_EIC_MUX PIN_PA11A_EIC_EXTINT11
#define CONF_BOARD_MATRIX_SENSE_2_PIN PIN_PA14
#define CONF_BOARD_MATRIX_SENSE_2_EIC_PIN MUX_PA14A_EIC_EXTINT14
#define CONF_BOARD_MATRIX_SENSE_2_EIC_MUX PIN_PA14A_EIC_EXTINT14
#define CONF_BOARD_MATRIX_SENSE_3_PIN PIN_PA09
#define CONF_BOARD_MATRIX_SENSE_3_EIC_PIN PIN_PA09A_EIC_EXTINT9
#define CONF_BOARD_MATRIX_SENSE_3_EIC_MUX MUX_PA09A_EIC_EXTINT9
#define CONF_BOARD_MATRIX_SENSE_4_PIN PIN_PA08
#define CONF_BOARD_MATRIX_SENSE_4_EIC_PIN PIN_PA08A_EIC_NMI
#define CONF_BOARD_MATRIX_SENSE_4_EIC_MUX MUX_PA08A_EIC_NMI
#define CONF_BOARD_MATRIX_SENSE_5_PIN PIN_PA15
#define CONF_BOARD_MATRIX_SENSE_5_EIC_PIN PIN_PA15A_EIC_EXTINT15
#define CONF_BOARD_MATRIX_SENSE_5_EIC_MUX MUX_PA15A_EIC_EXTINT15
#define CONF_BOARD_MATRIX_SENSE_6_PIN PIN_PA20
#define CONF_BOARD_MATRIX_SENSE_6_EIC_PIN PIN_PA20A_EIC_EXTINT4
#define CONF_BOARD_MATRIX_SENSE_6_EIC_MUX MUX_PA20A_EIC_EXTINT4
#define CONF_BOARD_MATRIX_SENSE_7_PIN PIN_PA21
#define CONF_BOARD_MATRIX_SENSE_7_EIC_PIN PIN_PA21A_EIC_EXTINT5
#define CONF_BOARD_MATRIX_SENSE_7_EIC_MUX MUX_PA21A_EIC_EXTINT5
#define CONF_BOARD_MATRIX_SENSE_8_PIN PIN_PA06
#define CONF_BOARD_MATRIX_SENSE_8_EIC_PIN PIN_PA06A_EIC_EXTINT6
#define CONF_BOARD_MATRIX_SENSE_8_EIC_MUX MUX_PA06A_EIC_EXTINT6

#endif /* USER_BOARD_H */
